import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en" className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-[#08090d] text-white overflow-x-hidden selection:bg-white/20">
        {/* Ambient Blobs */}
        <div className="fixed inset-0 z-[-1] overflow-hidden pointer-events-none">
          <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-blue-600/20 blur-[120px]" />
          <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full bg-purple-600/20 blur-[120px]" />
        </div>

        {/* Floating Nav Pill */}
        <nav className="fixed top-6 inset-x-0 mx-auto max-w-fit z-50 rounded-full bg-white/[0.03] backdrop-blur-2xl border border-white/10 px-8 py-3 shadow-[0_8_30px_rgb(0,0,0,0.5)]">
          <div className="flex items-center gap-6">
            <span className="text-sm font-bold tracking-widest uppercase bg-clip-text text-transparent bg-gradient-to-r from-white to-white/50">
              Pokédex OS
            </span>
            <div className="w-px h-4 bg-white/10" />
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              <span className="text-xs font-medium text-white/50 tracking-wider">SYSTEM ONLINE</span>
            </div>
          </div>
        </nav>

        <div className="pt-24 pb-12 flex-1 flex flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
